import type {
  GardenZone, Plant, JournalEntry, GardenTask,
  Device, SensorReading, CameraCapture, AutomationRule,
} from '@flowbond/core'

const now = new Date()
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000)
const daysAhead = (n: number) => new Date(now.getTime() + n * 86400000)

// ─── Zones ──────────────────────────────────────────────────────────────────

export const mockZones: GardenZone[] = [
  {
    id: 'zone-001',
    name: 'Main Veggie Bed',
    slug: 'main-veggie-bed',
    description: 'Primary production bed for annuals',
    locationNotes: 'East side of the yard, full sun 8h+',
    widthM: 1.2,
    lengthM: 4.0,
    sunExposure: 'full_sun',
    soilType: 'compost',
    irrigationType: 'drip',
    notes: 'Hugelkultur base layer with wood logs added Nov 2024',
    photoUrls: [],
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },
  {
    id: 'zone-002',
    name: 'Herb Spiral',
    slug: 'herb-spiral',
    description: 'Raised spiral for culinary herbs',
    locationNotes: 'Center of garden, near kitchen door',
    widthM: 2.0,
    lengthM: 2.0,
    sunExposure: 'full_sun',
    soilType: 'mixed',
    irrigationType: 'hand',
    notes: 'Stone spiral, drains well. Drought tolerant herbs on top.',
    photoUrls: [],
    createdAt: daysAgo(120),
    updatedAt: daysAgo(10),
  },
  {
    id: 'zone-003',
    name: 'Fruit Tree Guild',
    slug: 'fruit-tree-guild',
    description: 'Citrus + companion planting guild',
    locationNotes: 'South fence, sheltered from wind',
    widthM: 3.0,
    lengthM: 3.0,
    sunExposure: 'partial_shade',
    soilType: 'loam',
    irrigationType: 'drip',
    notes: 'Lemon + orange + dynamic accumulators. Chop and drop zone.',
    photoUrls: [],
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  // ── Lake Castle — first live garden ──
  {
    id: 'zone-lake-castle-back',
    gardenId: 'garden-lake-castle',
    name: 'Lake Castle — Back Garden',
    slug: 'lake-castle-back',
    description: 'First live FlowGarden zone. Tapo camera active, sensors coming.',
    locationNotes: 'Back of the building, Lake Castle',
    sunExposure: undefined,
    soilType: undefined,
    irrigationType: undefined,
    notes: 'Camera connected. First real measurements pending. This is the seed zone for the full Lake Castle garden system.',
    photoUrls: [],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'zone-004',
    name: 'Compost Bay',
    slug: 'compost-bay',
    description: 'Hot compost + worm bin area',
    locationNotes: 'Back corner, partial shade',
    widthM: 2.0,
    lengthM: 1.5,
    sunExposure: 'partial_shade',
    soilType: 'compost',
    irrigationType: 'none',
    notes: 'Three-bay hot compost. Pile 1 active, Pile 2 curing.',
    photoUrls: [],
    createdAt: daysAgo(150),
    updatedAt: daysAgo(5),
  },
]

// ─── Plants ──────────────────────────────────────────────────────────────────

export const mockPlants: Plant[] = [
  {
    id: 'plant-001',
    zoneId: 'zone-001',
    name: 'Tomato',
    variety: 'San Marzano',
    type: 'vegetable',
    status: 'flowering',
    plantedDate: daysAgo(60),
    expectedHarvestDate: daysAhead(30),
    depthCm: 10,
    spacingCm: 60,
    quantity: 4,
    notes: 'Heavy fruit set. Watch for blight.',
    photoUrls: [],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: 'plant-002',
    zoneId: 'zone-001',
    name: 'Cucumber',
    variety: 'Marketmore',
    type: 'vegetable',
    status: 'growing',
    plantedDate: daysAgo(45),
    expectedHarvestDate: daysAhead(15),
    depthCm: 5,
    spacingCm: 45,
    quantity: 3,
    notes: 'Climbing trellis. Needs consistent moisture.',
    photoUrls: [],
    createdAt: daysAgo(45),
    updatedAt: daysAgo(3),
  },
  {
    id: 'plant-003',
    zoneId: 'zone-001',
    name: 'Basil',
    variety: 'Genovese',
    type: 'herb',
    status: 'growing',
    plantedDate: daysAgo(30),
    depthCm: 2,
    spacingCm: 20,
    quantity: 6,
    notes: 'Planted near tomatoes as companion. Pinch tops weekly.',
    photoUrls: [],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(2),
  },
  {
    id: 'plant-004',
    zoneId: 'zone-002',
    name: 'Rosemary',
    variety: 'Tuscan Blue',
    type: 'herb',
    status: 'growing',
    plantedDate: daysAgo(180),
    depthCm: 5,
    spacingCm: 50,
    quantity: 1,
    notes: 'Established, very drought tolerant. Top of spiral.',
    photoUrls: [],
    createdAt: daysAgo(180),
    updatedAt: daysAgo(20),
  },
  {
    id: 'plant-005',
    zoneId: 'zone-002',
    name: 'Thyme',
    variety: 'Common',
    type: 'herb',
    status: 'growing',
    plantedDate: daysAgo(120),
    depthCm: 3,
    spacingCm: 25,
    quantity: 3,
    notes: 'Mid-spiral. Great ground cover.',
    photoUrls: [],
    createdAt: daysAgo(120),
    updatedAt: daysAgo(14),
  },
  {
    id: 'plant-006',
    zoneId: 'zone-003',
    name: 'Lemon Tree',
    variety: 'Eureka',
    type: 'tree',
    status: 'fruiting',
    plantedDate: daysAgo(730),
    expectedHarvestDate: daysAhead(60),
    depthCm: 30,
    spacingCm: 300,
    quantity: 1,
    notes: 'Second year. 12 lemons developing. Drip irrigation.',
    photoUrls: [],
    createdAt: daysAgo(730),
    updatedAt: daysAgo(7),
  },
  {
    id: 'plant-007',
    zoneId: 'zone-001',
    name: 'Lettuce',
    variety: 'Mixed Mesclun',
    type: 'vegetable',
    status: 'growing',
    plantedDate: daysAgo(21),
    expectedHarvestDate: daysAhead(14),
    depthCm: 1,
    spacingCm: 15,
    quantity: 20,
    notes: 'Cut and come again. Direct seeded in row.',
    photoUrls: [],
    createdAt: daysAgo(21),
    updatedAt: daysAgo(1),
  },
  {
    id: 'plant-008',
    zoneId: 'zone-001',
    name: 'Marigold',
    variety: 'French Dwarf',
    type: 'companion',
    status: 'flowering',
    plantedDate: daysAgo(50),
    depthCm: 2,
    spacingCm: 20,
    quantity: 8,
    notes: 'Pest deterrent border around tomatoes.',
    photoUrls: [],
    createdAt: daysAgo(50),
    updatedAt: daysAgo(5),
  },
]

// ─── Journal ─────────────────────────────────────────────────────────────────

export const mockJournal: JournalEntry[] = [
  {
    id: 'journal-001',
    zoneId: 'zone-001',
    entryDate: daysAgo(1),
    title: 'Morning check — all looking good',
    content: 'Tomatoes have set about 20 new flowers. Cucumbers climbing well on the trellis. Noticed aphids on 2 basil plants — removed by hand. Marigolds fully open. Added half a bucket of compost tea to the main bed.',
    weatherCondition: 'Sunny, light breeze',
    temperatureC: 26,
    humidityPct: 55,
    watered: true,
    compostAdded: false,
    pestsObserved: true,
    pestNotes: 'Aphids on basil, small colony, removed manually',
    photoUrls: [],
    tags: ['aphids', 'tomatoes', 'compost-tea'],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'journal-002',
    zoneId: 'zone-004',
    entryDate: daysAgo(3),
    title: 'Compost turn + kitchen scraps added',
    content: 'Turned Pile 1. Internal temp was 58°C — good hot compost activity. Added this week\'s kitchen scraps (no meat, mostly veggie peels and coffee grounds). Pile 2 looks almost ready, dark and earthy. Will test next week.',
    weatherCondition: 'Overcast',
    temperatureC: 20,
    watered: false,
    compostAdded: true,
    pestsObserved: false,
    photoUrls: [],
    tags: ['compost', 'hot-compost', 'kitchen-scraps'],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'journal-003',
    zoneId: 'zone-003',
    entryDate: daysAgo(7),
    title: 'Lemon tree — fruit sizing up',
    content: 'Lemon tree looking healthy. 12 fruits visible, all sizing up nicely. Applied liquid seaweed fertilizer. Noticed some yellowing on a few lower leaves — may be nitrogen or magnesium. Will monitor and add a small worm casting top dressing this weekend.',
    weatherCondition: 'Clear, hot',
    temperatureC: 30,
    watered: true,
    compostAdded: false,
    pestsObserved: false,
    photoUrls: [],
    tags: ['lemon', 'fruit-guild', 'fertilizer', 'yellowing-leaves'],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'journal-004',
    zoneId: undefined,
    entryDate: daysAgo(14),
    title: 'Planning new guild — companion planting layout',
    content: 'Spent the morning sketching a new three-sisters guild for the main bed. Corn + beans + squash. Reading about spacing — need 1m² minimum per corn stalk. Will start seeds in 2 weeks for autumn planting. Also ordered neem oil for future pest prevention.',
    watered: false,
    compostAdded: false,
    pestsObserved: false,
    photoUrls: [],
    tags: ['planning', 'three-sisters', 'companion-planting'],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: 'journal-005',
    zoneId: 'zone-002',
    entryDate: daysAgo(20),
    title: 'Herb spiral — pruning session',
    content: 'Cut back rosemary by 30%. Harvested a big bunch of thyme for drying. Planted 2 new lemon verbena seedlings at the base of the spiral where moisture stays higher. Spiral stones shifted — re-set 3 of them. Looking beautiful.',
    weatherCondition: 'Morning sun, afternoon cloud',
    temperatureC: 22,
    watered: true,
    compostAdded: true,
    pestsObserved: false,
    photoUrls: [],
    tags: ['herbs', 'pruning', 'harvest', 'lemon-verbena'],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
]

// ─── Tasks ────────────────────────────────────────────────────────────────────

export const mockTasks: GardenTask[] = [
  {
    id: 'task-001',
    zoneId: 'zone-001',
    title: 'Water main veggie bed',
    description: 'Deep watering — check soil moisture first. 20 min drip.',
    status: 'pending',
    priority: 'high',
    dueDate: now,
    rewardPoints: 10,
    proofRequired: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'task-002',
    zoneId: 'zone-001',
    plantId: 'plant-001',
    title: 'Inspect tomatoes for blight',
    description: 'Check lower leaves for dark spots. Remove affected leaves and bag. Apply copper spray if more than 3 plants affected.',
    status: 'pending',
    priority: 'high',
    dueDate: daysAhead(1),
    rewardPoints: 15,
    proofRequired: true,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'task-003',
    zoneId: 'zone-004',
    title: 'Add kitchen scraps to compost pile 1',
    description: 'Empty kitchen caddy into active pile. Cover with dry material (straw or cardboard).',
    status: 'done',
    priority: 'medium',
    dueDate: daysAgo(1),
    rewardPoints: 5,
    proofRequired: false,
    completedAt: daysAgo(1),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: 'task-004',
    zoneId: 'zone-003',
    plantId: 'plant-006',
    title: 'Apply worm casting top dressing to lemon tree',
    description: '2L of finished worm castings around drip line. Water in well afterwards.',
    status: 'pending',
    priority: 'medium',
    dueDate: daysAhead(2),
    rewardPoints: 10,
    proofRequired: false,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: 'task-005',
    zoneId: 'zone-001',
    plantId: 'plant-007',
    title: 'Harvest lettuce — cut and come again',
    description: 'Cut outer leaves 5cm above base. Leave center intact.',
    status: 'pending',
    priority: 'medium',
    dueDate: daysAhead(3),
    rewardPoints: 10,
    proofRequired: false,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: 'task-006',
    zoneId: undefined,
    title: 'Check and flush drip irrigation lines',
    description: 'Open all end-caps, flush 2 minutes, check for blockages or emitters that are not flowing.',
    status: 'pending',
    priority: 'low',
    dueDate: daysAhead(7),
    rewardPoints: 20,
    proofRequired: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'task-007',
    zoneId: 'zone-001',
    title: 'Label all plants in main bed',
    description: 'Use timber stakes + marker. Include: plant name, variety, date planted.',
    status: 'in_progress',
    priority: 'low',
    dueDate: daysAhead(5),
    rewardPoints: 10,
    proofRequired: true,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
]

// ─── Devices ─────────────────────────────────────────────────────────────────

export const mockDevices: Device[] = [
  // ── Lake Castle (real hardware, first live garden) ──
  {
    id: 'cam-lake-castle-back',
    zoneId: 'zone-lake-castle-back',
    name: 'Tapo C104 — Back Garden',
    type: 'camera',
    status: 'offline',
    lastSeenAt: undefined,
    metadata: {
      model: 'Tapo C104',
      location: 'Lake Castle back garden',
      stream: 'stream1',
      resolution: '1080p',
      live: true,
    },
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  // ── Planned hardware (future) ──
  {
    id: 'device-pi-001',
    zoneId: 'zone-001',
    name: 'Garden Pi Node 1',
    type: 'raspberry_pi',
    status: 'offline',
    firmwareVersion: undefined,
    lastSeenAt: undefined,
    metadata: { model: 'Raspberry Pi 4', planned: true },
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'device-soil-001',
    zoneId: 'zone-001',
    name: 'Soil Sensor — Main Bed',
    type: 'soil_sensor',
    status: 'offline',
    lastSeenAt: undefined,
    metadata: { sensor: 'Capacitive v2', planned: true },
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'device-soil-002',
    zoneId: 'zone-003',
    name: 'Soil Sensor — Fruit Guild',
    type: 'soil_sensor',
    status: 'offline',
    lastSeenAt: undefined,
    metadata: { sensor: 'Capacitive v2', planned: true },
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'device-water-001',
    zoneId: undefined,
    name: 'Water Tank Level Sensor',
    type: 'water_level_sensor',
    status: 'offline',
    lastSeenAt: undefined,
    metadata: { tank_capacity_L: 1000, planned: true },
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
]

// ─── Sensor Readings (mock — manual entry) ────────────────────────────────────

export const mockSensorReadings: SensorReading[] = [
  {
    id: 'reading-001',
    zoneId: 'zone-001',
    readingType: 'soil_moisture',
    value: 42,
    unit: '%',
    source: 'manual',
    recordedAt: daysAgo(1),
    createdAt: daysAgo(1),
  },
  {
    id: 'reading-002',
    zoneId: 'zone-003',
    readingType: 'soil_moisture',
    value: 28,
    unit: '%',
    source: 'manual',
    recordedAt: daysAgo(2),
    createdAt: daysAgo(2),
  },
  {
    id: 'reading-003',
    zoneId: 'zone-001',
    readingType: 'temperature',
    value: 26,
    unit: '°C',
    source: 'manual',
    recordedAt: daysAgo(1),
    createdAt: daysAgo(1),
  },
  {
    id: 'reading-004',
    zoneId: 'zone-001',
    readingType: 'humidity',
    value: 62,
    unit: '%',
    source: 'manual',
    recordedAt: daysAgo(1),
    createdAt: daysAgo(1),
  },
  {
    id: 'reading-005',
    zoneId: undefined,
    readingType: 'water_level',
    value: 75,
    unit: '%',
    source: 'manual',
    recordedAt: daysAgo(3),
    createdAt: daysAgo(3),
  },
]

// ─── Automation Rules ────────────────────────────────────────────────────────

export const mockAutomationRules: AutomationRule[] = [
  {
    id: 'rule-001',
    name: 'Alert when soil moisture below 30%',
    triggerType: 'soil_moisture_below',
    condition: { threshold: 30, zone_id: 'zone-001', reading_type: 'soil_moisture' },
    actionType: 'notify',
    actionConfig: { message: 'Main bed soil moisture is low. Consider watering.' },
    enabled: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'rule-002',
    name: 'Create daily watering task at 7am',
    triggerType: 'schedule',
    condition: { cron: '0 7 * * *' },
    actionType: 'create_task',
    actionConfig: {
      title: 'Morning check and water',
      priority: 'high',
      zone_id: 'zone-001',
    },
    enabled: false,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: 'rule-003',
    name: 'AI review garden weekly',
    triggerType: 'schedule',
    condition: { cron: '0 9 * * 1' },
    actionType: 'ai_review',
    actionConfig: { prompt: 'Summarize garden health and suggest 3 priority actions.' },
    enabled: false,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
]

// ─── In-memory store (allows mutations during session) ───────────────────────

export const store = {
  zones: [...mockZones],
  plants: [...mockPlants],
  journal: [...mockJournal],
  tasks: [...mockTasks],
  devices: [...mockDevices],
  sensorReadings: [...mockSensorReadings],
  cameraCaptures: [] as CameraCapture[],
  automationRules: [...mockAutomationRules],
}
