/**
 * FlowRoom — Room #1
 * apps/flowroom/src/content/rooms/1mwd.ts
 *
 * 1 Million Women Dance × DANZ — Build Proposal
 * Client: House of Tigris Media (Vandana Hart)
 *
 * Seeds `flowroom_blocks`. Run `pnpm seed:room 1mwd` after any edit.
 * Seeding is an UPSERT on (room_id, block_key) — safe to re-run.
 *
 * DO NOT RENAME KEYS. See types.ts.
 */

import type { RoomContent } from '../types';

export const room1mwd: RoomContent = {
  slug: 'REPLACE_AT_SEED', // nanoid(22) generated by the seed script
  title: '1 Million Women Dance × DANZ — Build Proposal',
  clientName: 'House of Tigris Media',

  theme: {
    void: '#120A16',
    panel: '#1B1022',
    raise: '#241630',
    bone: '#F5EFE6',
    mute: '#9E8FA6',
    gold: ['#A87C2E', '#F3D89A'],
    rainbow: ['#FF6BB8', '#B36BFF', '#4FA8FF', '#FFD84F'],
    causeColors: {
      water: '#45D6E0',
      forests: '#4FD98B',
      air: '#B9A7FF',
      women: '#FF6B6B',
      culture: '#FFD84F',
    },
    display: 'Cormorant Garamond',
    body: 'Manrope',
    mono: 'IBM Plex Mono',
    logoKey: 'rooms/1mwd/brand/goddess-mark.png',
  },

  blocks: [
    /* ============================================================ */
    /* HERO                                                          */
    /* ============================================================ */
    {
      key: 'hero.thesis',
      section: 'hero',
      kind: 'hero',
      annotatable: false,
      eyebrow: 'House of Tigris Media × FlowBond · August 2026',
      headline: 'Let\'s make the world dance _in one heart_.',
      lede:
        'The mission is already whole. What it has been missing is a technology partner who takes the whole build off your hands rather than adding to your list — one person accountable, one architecture underneath all four brands, and a platform that already exists instead of one that has to be invented. Everything below is what that looks like, in order, with dates.',
      chips: [
        { label: 'Mission aligned · partnership signed', status: 'neutral' },
        { label: 'Identity, movement & support live', status: 'live' },
        { label: '12 weeks to launch', status: 'wire' },
      ],
    },

    /* ============================================================ */
    /* 01 — SYSTEM                                                   */
    /* ============================================================ */
    {
      key: 'system.head',
      section: 'system',
      kind: 'section_head',
      annotatable: false,
      index: '01',
      eyebrow: 'Architecture',
      title: 'Four brands. One account.',
      dek:
        'Your brand architecture is right: each site does one job and never advertises its siblings. But four front doors normally means four sign-ups, four member lists and four places data goes to die. It doesn\'t have to. One identity sits underneath all of them — invisible to the visitor, decisive for the business.',
    },
    {
      key: 'system.map',
      section: 'system',
      kind: 'site_map',
      owner: 'shared',
      sites: [
        { domain: 'vandanahart.com', role: 'The person. Speaking, book, bio.' },
        { domain: '1billionhearts.com', role: 'The company. Mission, investors, press.' },
        { domain: 'wespeakdance.com', role: 'The show. Trailer, episodes, Netflix.' },
        { domain: '1millionwomendance.com', role: 'The front door. Sign-up, app, the raise.' },
      ],
      spine: {
        title: 'One account underneath — FBID',
        body:
          'A woman signs up once at 1MWD and is already known at We Speak Dance and 1 Billion Hearts. When 1BH becomes the primary engine, her history moves with her. No migration, no rebuild, no lost cohort. This is the single most valuable thing we can put in before launch, and the single hardest thing to retrofit after.',
      },
    },
    {
      key: 'system.value_s2',
      section: 'system',
      kind: 'card',
      title: 'What it buys you at S2',
      body:
        'The end-card sends viewers to 1MWD. They sign up there. When the show\'s own site later sells a press kit or a class, they\'re already a member — the conversion happens once and counts everywhere.',
    },
    {
      key: 'system.value_investors',
      section: 'system',
      kind: 'card',
      title: 'What it buys you with investors',
      body:
        'One member number for the whole house instead of three unreconciled follower counts. Cohort retention across brands is the metric a Series A actually underwrites.',
    },
    {
      key: 'system.value_brands',
      section: 'system',
      kind: 'card',
      title: 'What it buys you with brands',
      body:
        'A partner paying $200K wants to know who they reached and what those women did next. That answer lives in the identity layer, not in Instagram analytics.',
    },

    /* ============================================================ */
    /* 02 — FLOW                                                     */
    /* ============================================================ */
    {
      key: 'flow.head',
      section: 'flow',
      kind: 'section_head',
      annotatable: false,
      index: '02',
      eyebrow: 'The member flow',
      title: 'Five stages, and the rail under each one.',
      dek:
        'This is your MVP feature set, unchanged, with the system that powers each step and its honest status today. Live means running in production right now. Wire means we connect existing pieces. Later means deliberately out of MVP, per your roadmap.',
    },
    {
      key: 'flow.01_join',
      section: 'flow',
      kind: 'stage',
      owner: 'steph',
      n: '01',
      title: 'She joins and gets her move',
      body:
        'Sign-up, then a short video upload, a cause colour, and one line naming her dream. Video is transcoded, thumbnailed and stored, and a signed record of authorship is attached the moment it lands — so the move is provably hers before it ever spreads.',
      rail: 'FBID sign-in · R2 media pipeline · ORIGO authorship record',
      statuses: [
        { label: 'Identity live', status: 'live' },
        { label: 'Upload to wire', status: 'wire' },
      ],
    },
    {
      key: 'flow.02_chain',
      section: 'flow',
      kind: 'stage',
      owner: 'steph',
      n: '02',
      title: 'She shares it — and the chain starts',
      body:
        'Every share generates a link and QR that carries her identity. Whoever taps "I danced this" is recorded as hers, and their share carries both. Self-reported for MVP, exactly as you scoped it — but recorded as a parent-child chain rather than a number going up.',
      rail: 'FlowShare referral graph · attributed short links · QR',
      statuses: [
        { label: 'Referral rail live', status: 'live' },
        { label: 'Chain logic to wire', status: 'wire' },
      ],
    },
    {
      key: 'flow.03_hearts',
      section: 'flow',
      kind: 'stage',
      owner: 'vandana',
      n: '03',
      title: 'She earns Dance Hearts — and gives them',
      body:
        'Hearts land in a real ledger, not a column in her profile row. She earns when women dance her move, and she spends when she votes for someone else\'s cause. Every heart has a source, a destination and a timestamp, so the spotlight at the summit can be defended in public.',
      rail: 'Double-entry append-only ledger · closed-loop, non-cash',
      statuses: [
        { label: 'Ledger engine live', status: 'live' },
        { label: 'Heart rules to wire', status: 'wire' },
      ],
    },
    {
      key: 'flow.04_discovery',
      section: 'flow',
      kind: 'stage',
      owner: 'steph',
      n: '04',
      title: 'She finds her people',
      body:
        'Browse by cause colour, see who\'s closest to a million, discover a grassroots leader next to a name she recognises. Ranked by hearts given as well as received, so the feed rewards women who lift others instead of whoever shouts loudest.',
      rail: 'Discovery feed · cause-colour index · dual leaderboard',
      statuses: [{ label: 'To build', status: 'wire' }],
    },
    {
      key: 'flow.05_monthly',
      section: 'flow',
      kind: 'stage',
      owner: 'shared',
      n: '05',
      title: 'She shows up every month',
      body:
        'The monthly class page: guest teacher, guest speaker, your segment, the Womb Movement circle, replay archive. Membership at $75/year and per-class tickets both run through it, and the guest teacher is paid automatically out of the same transaction — funds go from the member straight to the teacher\'s own account. We never hold the money.',
      rail: 'FlowShare no-custody splits · Stripe · membership billing',
      statuses: [
        { label: 'Payments live', status: 'live' },
        { label: 'Class page to build', status: 'wire' },
      ],
    },
    {
      key: 'flow.autoclip',
      section: 'flow',
      kind: 'callout',
      owner: 'steph',
      title: 'The auto-clip is not a nice-to-have',
      body: [
        'Your growth loop is Instagram-first, and it depends on every upload producing a branded, shareable clip with the cause-colour overlay, the live count and the hashtag — plus milestone graphics at 10K, 100K and 500K. That\'s a render worker, it\'s cheap, and it goes in the MVP. A woman who has to make her own graphic doesn\'t share; a woman handed one does.',
      ],
    },

    /* ============================================================ */
    /* 03 — CHAIN                                                    */
    /* ============================================================ */
    {
      key: 'chain.head',
      section: 'chain',
      kind: 'section_head',
      annotatable: false,
      index: '03',
      eyebrow: 'The mechanic',
      title: 'Why the Dance Chain has to be a graph',
      dek:
        'This is the one place where I\'d push back on the simplest version of the spec — and the reason is money, not engineering taste.',
    },
    {
      key: 'chain.compare',
      section: 'chain',
      kind: 'compare',
      owner: 'shared',
      left: {
        title: 'If it\'s a counter',
        body:
          'Amara\'s number says 218,000. That\'s all anyone ever knows. You can\'t tell who brought those women, you can\'t tell whether 200,000 of them came from one bot farm, you can\'t tell a brand partner which activation produced them, and the moment a real prize is attached, the number becomes worth gaming and impossible to defend.',
        note: 'One integer. No provenance. No recourse.',
      },
      right: {
        title: 'If it\'s a graph',
        body:
          'Amara\'s number is the sum of a tree you can walk. You can see that 40,000 came through one woman in Lagos who should be spotlighted. You can prune a poisoned branch without touching the honest ones. You can pay a referral share. You can show a brand exactly what its campaign grew. And "closest to a million" survives an audit.',
        note: 'Same UX for her. Completely different asset for you.',
      },
    },
    {
      key: 'chain.world',
      section: 'chain',
      kind: 'world',
      annotatable: false,
      title: 'Step inside the chain',
      body:
        'An explorable space where every point of light is one woman and every thread is one invitation. Drag to look, scroll to move.',
      splatKey: 'rooms/1mwd/worlds/chain-chamber.ply',
      posterVideoKey: 'rooms/1mwd/worlds/chain-chamber-orbit.mp4',
      hint: 'Drag to look around',
    },
    {
      key: 'chain.fraud',
      section: 'chain',
      kind: 'callout',
      owner: 'steph',
      tone: 'warn',
      title: 'Fraud control belongs in the MVP, not phase two',
      body: [
        'Your roadmap correctly defers wearable verification. But prizes and grants get announced live at the summit, which means the leaderboard becomes adversarial the day it goes public — well before any wearable exists. The MVP therefore ships with: one count per account per move, device and session de-duplication, velocity limits, chain-depth caps, and a quarantine flag that lets you exclude a branch from ranking without deleting anyone.',
        'None of this is visible to an honest participant. All of it is unbuildable after the fact, because you can\'t retroactively find out where a number came from.',
      ],
    },
    {
      key: 'chain.trademark',
      section: 'chain',
      kind: 'card',
      owner: 'vandana',
      title: 'Trademark note',
      body:
        'Your Year 1 budget files Global Dance Chain™. Worth filing the software classes alongside the media ones while the mark is being registered — the mechanic is the licensable asset here, and Zumba is the precedent you\'re citing for exactly that reason.',
    },
    {
      key: 'chain.verified_tier',
      section: 'chain',
      kind: 'card',
      title: 'Verified tier, pre-cut',
      body:
        'Every count carries one field: how it was confirmed. Self-reported at launch, verified when a woman is on a floor with a code on the screen, and biometric when she has a strap on — all three already exist in DANZ.NOW. Old data stays valid whichever way it arrived; nobody\'s progress is ever reset.',
    },
    {
      key: 'chain.referral_share',
      section: 'chain',
      kind: 'card',
      title: 'Referral share, pre-cut',
      body:
        'Because the record knows who brought whom, recognising a woman for the women she brought — extra hearts, a featured slot, a place at the retreat — is a configuration change rather than a rebuild. Generosity becomes something the system can see and reward on its own.',
    },

    /* ============================================================ */
    /* 04 — DANZ.NOW · the gamified layer, already built             */
    /* ============================================================ */
    {
      key: 'danz.head',
      section: 'danz',
      kind: 'section_head',
      annotatable: false,
      index: '04',
      eyebrow: 'Already running',
      title: 'The gamified layer is not a proposal. It\'s live.',
      dek:
        'Everything in the last section describes a mechanic we would build for you. This section describes one we already built, shipped, and broke on purpose until it held. DANZ.NOW runs at danz.now today: real dance floors, verified movement, a live leaderboard and an append-only XP ledger — on the same identity layer 1MWD would sit on.',
    },
    {
      key: 'danz.floors',
      section: 'danz',
      kind: 'card',
      title: 'Floors, QR check-in, live leaderboard',
      body:
        'An organiser opens a floor and gets a QR. Dancers scan it, join, and the leaderboard updates live while they move. Check-in is broken down by how it happened — geo, ticket, or referred by another dancer — which is the same parent-child record the Dance Chain needs.',
      tech: 'danz.now · Cloudflare Workers · FBID identity',
    },
    {
      key: 'danz.xp',
      section: 'danz',
      kind: 'callout',
      owner: 'steph',
      title: 'The client never gets to say how much it earned',
      body: [
        'XP is never accepted from the browser. The server recomputes it from active seconds, clamped to wall-clock time and multiplied by measured intensity, then writes it to an append-only ledger with a dedupe key. We tested it in production by submitting a claim for 99,999 XP. It was recorded as 15.',
        'This is the fraud argument from the previous section, except it is not an argument — it is a number you can go and reproduce. Every control the 1MWD leaderboard needs at the summit is already written, already adversarial, and already carrying real traffic.',
      ],
    },
    {
      key: 'danz.heartsync',
      section: 'danz',
      kind: 'card',
      title: 'HeartSync — real heart rate, no partner deal required',
      body:
        'Two dancers open a sync and the app reads their actual heart rate over Bluetooth, straight from any standard chest strap. The server derives the match score from the stored beat streams — correlation and closeness — and pays both sides from the ledger. Two fresh accounts tested at 96% quality, 51 XP each, and a replayed finalise paid zero.',
      tech: 'Web Bluetooth GATT 0x180D · server-authoritative scoring',
    },
    {
      key: 'danz.wearables_note',
      section: 'danz',
      kind: 'card',
      owner: 'vandana',
      title: 'What this does to your Phase 2',
      body:
        'Your roadmap defers wearable verification until after MVP, on the assumption it needs Whoop and Oura partnerships. It does not. Heart rate already works with no partner API and no OAuth — the Whoop and Oura integrations become a convenience for people who already own one, not the thing that unlocks verified movement.',
    },
    {
      key: 'danz.host',
      section: 'danz',
      kind: 'card',
      title: 'Organiser console, already shipped',
      body:
        'Live dancers, XP, active time and peak; the check-in breakdown; the floor QR; a bounded editor for the XP economy; the leaderboard; and ending the floor. Every action refuses at the server if the floor is not yours. This is the monthly class page, most of the way built, before we start.',
      tech: 'RPC-enforced ownership · bounded economy editor',
    },
    {
      key: 'danz.honest',
      section: 'danz',
      kind: 'callout',
      tone: 'warn',
      owner: 'steph',
      title: 'One honest limit, so nobody is surprised in a demo',
      body: [
        'Heart-rate pairing needs Web Bluetooth, and Apple does not ship it in any iOS browser. On an iPhone the app says so plainly instead of showing a button that cannot work. Everything else — floors, movement XP, leaderboards, check-in — works fine on iPhone, and a native iOS app using HealthKit is the route to heart rate there when we want it.',
      ],
    },
    {
      key: 'danz.fit',
      section: 'danz',
      kind: 'prose',
      owner: 'shared',
      title: 'How it lands inside 1MWD',
      body: [
        'The monthly class becomes a floor: a QR on the stream, a live leaderboard of who is actually dancing, and a verified record of it afterwards. The summit becomes a floor with ten thousand people on it. "I danced this" stops being self-reported the moment a woman is standing in a room with a code on the screen.',
        'None of that is new construction. It is configuration of a system that is already carrying traffic — which is the whole reason the twelve weeks are twelve weeks.',
      ],
    },

    /* ============================================================ */
    /* 05 — HEARTS                                                   */
    /* ============================================================ */
    {
      key: 'hearts.head',
      section: 'hearts',
      kind: 'section_head',
      annotatable: false,
      index: '05',
      eyebrow: 'The currency',
      title: 'Dance Hearts — support you can actually feel',
      dek:
        'Two functions, exactly as your roadmap specifies: earn hearts when women dance your move, give hearts to lift someone else\'s cause. What makes them matter is what they turn into — merch, tickets, experiences, a place at a retreat — and what keeps them honest is that every one has a source, a destination and a timestamp.',
    },
    {
      key: 'hearts.closed_loop',
      section: 'hearts',
      kind: 'card',
      owner: 'shared',
      title: 'Hearts buy real things',
      body:
        'Hearts are a supportive points system, nothing more complicated than that. A woman earns them when others dance her move, and she spends them on things she actually wants — merch, tickets to the monthly class, invitations to experiences, a place at a retreat — or she gives them away to lift another woman\'s cause. They are never bought and never cashed out, which keeps the whole thing simple, generous and clean everywhere you operate.',
      tech: 'Merch · tickets · experiences · retreats',
    },
    {
      key: 'hearts.append_only',
      section: 'hearts',
      kind: 'card',
      title: 'Append-only, so the summit is defensible',
      body:
        'Nothing is ever overwritten — every heart earned, given and spent is a permanent entry. When you announce grants live on stage, you can show the working. "We didn\'t pick favourites" is only credible if the record exists and predates the decision.',
      tech: 'Double-entry · immutable · exportable',
    },
    {
      key: 'hearts.four_rules',
      section: 'hearts',
      kind: 'callout',
      owner: 'vandana',
      due: '2026-08-14',
      title: 'Four rules only you can set',
      body: [
        'These are product decisions, not engineering ones, and everything downstream waits on them. One: how many hearts does a woman earn when someone dances her move? Two: how many hearts does she get to give per month, and do they refill? Three: does giving a heart cost her anything from her own earned balance, or come from a separate monthly allowance? Four: is there a cap on how many hearts one woman can send to one other woman, so a small group can\'t crown each other?',
        'My recommendation: a separate monthly giving allowance that refills and does not touch her earned balance, with a per-recipient cap. It makes generosity free, keeps the two numbers from contaminating each other, and gives you a clean monthly engagement pulse.',
      ],
    },

    /* ============================================================ */
    /* 05 — INVENTORY                                                */
    /* ============================================================ */
    {
      key: 'inventory.head',
      section: 'inventory',
      kind: 'section_head',
      annotatable: false,
      index: '06',
      eyebrow: 'Honest inventory',
      title: 'What exists, what we wire, what waits',
      dek: 'No marketing in this table. This is the actual state of the systems on the day we start.',
    },
    { key: 'inventory.identity', section: 'inventory', kind: 'table_row', system: 'Identity — FBID', does: 'One member account across all four sites; profile, session, permissions', status: 'live' },
    { key: 'inventory.split_payments', section: 'inventory', kind: 'table_row', system: 'Split payments', does: 'Membership and class income paid out to guest teachers and community leads directly; we never hold funds', status: 'live' },
    { key: 'inventory.referral_graph', section: 'inventory', kind: 'table_row', system: 'Referral graph', does: 'The engine that records who brought whom — becomes the Dance Chain', status: 'live' },
    { key: 'inventory.ledger', section: 'inventory', kind: 'table_row', system: 'Ledger engine', does: 'Append-only double-entry accounting — becomes Dance Hearts', status: 'live' },
    { key: 'inventory.infra', section: 'inventory', kind: 'table_row', system: 'Hosting & database', does: 'Global edge delivery, media storage, scheduled jobs, backups', status: 'live' },
    { key: 'inventory.danz_floors', section: 'inventory', kind: 'table_row', system: 'Floors & verified XP', does: 'QR check-in, server-authoritative movement scoring, live leaderboard, append-only XP ledger — running on danz.now', status: 'live' },
    { key: 'inventory.danz_heartsync', section: 'inventory', kind: 'table_row', system: 'HeartSync', does: 'Real heart rate over Bluetooth, server-derived match score, paid from the ledger — no partner API needed', status: 'live' },
    { key: 'inventory.danz_host', section: 'inventory', kind: 'table_row', system: 'Organiser console', does: 'Live floor stats, check-in breakdown, QR, bounded XP economy editor, leaderboard', status: 'live' },
    { key: 'inventory.dev_accounts', section: 'inventory', kind: 'table_row', system: 'App store accounts', does: 'FlowBond publishes under its own Apple and Google developer accounts', status: 'live' },
    { key: 'inventory.upload', section: 'inventory', kind: 'table_row', system: 'Move upload', does: 'Video capture, transcode, thumbnail, moderation queue, authorship record', status: 'wire' },
    { key: 'inventory.dance_chain', section: 'inventory', kind: 'table_row', system: 'Dance Chain', does: 'Attributed links and QR, "I danced this", chain tree, fraud controls', status: 'wire' },
    { key: 'inventory.hearts_rules', section: 'inventory', kind: 'table_row', system: 'Dance Hearts rules', does: 'Earn and give logic, monthly allowance, caps, vote resolution', status: 'wire' },
    { key: 'inventory.feed', section: 'inventory', kind: 'table_row', system: 'Discovery feed', does: 'Cause-colour browse, dual leaderboard, featured women carousel', status: 'wire' },
    { key: 'inventory.class_page', section: 'inventory', kind: 'table_row', system: 'Monthly class page', does: 'Teacher and speaker bios, ticketing, live link, replay archive', status: 'wire' },
    { key: 'inventory.autoclip', section: 'inventory', kind: 'table_row', system: 'Auto-clip renderer', does: 'Branded share clip per upload, milestone graphics at 10K / 100K / 500K', status: 'wire' },
    { key: 'inventory.mobile', section: 'inventory', kind: 'table_row', system: 'Mobile app', does: 'iOS and Android, built on the DANZ codebase', status: 'wire' },
    { key: 'inventory.wearables', section: 'inventory', kind: 'table_row', system: 'Wearable verification', does: 'Whoop and Oura first, per your partner sequence', status: 'later' },
    { key: 'inventory.rewards', section: 'inventory', kind: 'table_row', system: 'Perks catalogue', does: 'Redeeming hearts for merch, class tickets, experiences and retreat places — fulfilment and inventory', status: 'later' },
    { key: 'inventory.prize_payout', section: 'inventory', kind: 'table_row', system: 'Automated prize payout', does: 'Grant and prize disbursement at scale', status: 'later' },
    {
      key: 'inventory.exclusions_note',
      section: 'inventory',
      kind: 'prose',
      body: [
        'The items marked Later are the ones your roadmap explicitly holds back from MVP, and I agree with holding every one of them. The only change I am making is cutting the sockets now, so that switching any of them on later is a configuration change rather than a rebuild.',
      ],
    },

    /* ============================================================ */
    /* 06 — PLAN                                                     */
    /* ============================================================ */
    {
      key: 'plan.head',
      section: 'plan',
      kind: 'section_head',
      annotatable: false,
      index: '07',
      eyebrow: 'Delivery',
      title: 'Twelve weeks to a public MVP',
      dek:
        'Starting the week of 17 August, first cohort onboarding opens in week 9 and the public launch lands the first week of November — ahead of any We Speak Dance S2 end-card date you set. Each phase ships something real; nothing waits for everything.',
    },
    {
      key: 'plan.wk01_02',
      section: 'plan',
      kind: 'timeline_step',
      owner: 'shared',
      due: '2026-08-28',
      when: 'WEEKS 1–2',
      dates: '17–28 Aug',
      title: 'Decisions, foundations, and the front door',
      body:
        'We lock the four Dance Hearts rules, what counts as a dance, and the cause-colour slate. Domains connect, identity goes live across the four sites, and 1millionwomendance.com ships as a real page with a working waitlist behind it.',
      ships: 'Live site, live waitlist, one member account across all four brands',
    },
    {
      key: 'plan.wk03_05',
      section: 'plan',
      kind: 'timeline_step',
      owner: 'steph',
      due: '2026-09-18',
      when: 'WEEKS 3–5',
      dates: '31 Aug–18 Sep',
      title: 'My Move and the Dance Chain',
      body:
        'Video upload with transcode and moderation queue, cause colour and dream statement, authorship record on every move. Then the chain itself: attributed links, QR, "I danced this", the parent-child tree, and the full fraud control set.',
      ships: 'A woman can upload her move and watch a real chain grow from it',
    },
    {
      key: 'plan.wk06_07',
      section: 'plan',
      kind: 'timeline_step',
      owner: 'steph',
      due: '2026-10-02',
      when: 'WEEKS 6–7',
      dates: '21 Sep–2 Oct',
      title: 'Dance Hearts and the feed',
      body:
        'Earn and give both running on the ledger, monthly allowance, per-recipient caps. Discovery by cause colour, dual leaderboard ranking on hearts given as well as received, featured women carousel.',
      ships: 'The two-sided loop — women boosting each other, visibly',
    },
    {
      key: 'plan.wk08_09',
      section: 'plan',
      kind: 'timeline_step',
      owner: 'shared',
      due: '2026-10-16',
      when: 'WEEKS 8–9',
      dates: '5–16 Oct',
      title: 'Money, class, and the share engine',
      body:
        'Membership billing at $75/year, monthly class page with ticketing, guest teacher paid automatically from the same transaction. Auto-clip renderer and milestone graphics go live. First cohort onboarding opens — invite-only.',
      ships: 'First revenue, first paid teacher, first cohort inside',
    },
    {
      key: 'plan.wk10_11',
      section: 'plan',
      kind: 'timeline_step',
      owner: 'shared',
      due: '2026-10-30',
      when: 'WEEKS 10–11',
      dates: '19–30 Oct',
      title: 'Mobile, hardening, and the first real class',
      body:
        'iOS and Android submitted for review. Load testing against a launch-day spike, moderation workflow handed to your team, analytics dashboard for the metrics investors will ask about. We run one full monthly class end to end with the cohort while it\'s still safe to break.',
      ships: 'Apps in review, one complete monthly class delivered live',
    },
    {
      key: 'plan.wk12',
      section: 'plan',
      kind: 'timeline_step',
      owner: 'shared',
      due: '2026-11-06',
      when: 'WEEK 12',
      dates: '2–6 Nov',
      title: 'Public launch',
      body:
        'Doors open. Waitlist converts, the Instagram loop runs on real moves from the cohort, and every asset needed for the S2 end-card is already live at the URL it points to.',
      ships: 'Public MVP, ready for the show to point at it',
    },

    /* ============================================================ */
    /* 07 — NEED                                                     */
    /* ============================================================ */
    {
      key: 'need.head',
      section: 'need',
      kind: 'section_head',
      annotatable: false,
      index: '08',
      eyebrow: 'Your side',
      title: 'What we need from you',
      dek:
        'Nothing here is large, but the first group blocks everything. If the decisions in the first column land in week one, nothing else on this page slips.',
    },

    // — Decisions
    { key: 'need.dec.hearts_rules', section: 'need', kind: 'need_item', group: 'decisions', groupLabel: 'Decisions', groupWhen: 'Week 1', owner: 'vandana', due: '2026-08-14', label: 'The four Dance Hearts rules', detail: 'Earn rate, monthly giving allowance, whether giving costs earned balance, per-recipient cap' },
    { key: 'need.dec.what_counts', section: 'need', kind: 'need_item', group: 'decisions', groupLabel: 'Decisions', groupWhen: 'Week 1', owner: 'vandana', due: '2026-08-14', label: 'What counts as "I danced this"', detail: 'A tap, a video reply, or either' },
    { key: 'need.dec.cause_colors', section: 'need', kind: 'need_item', group: 'decisions', groupLabel: 'Decisions', groupWhen: 'Week 1', owner: 'vandana', due: '2026-08-14', label: 'Final cause-colour slate', detail: 'Water, Forests, Air, Women, Culture confirmed, or a different set' },
    { key: 'need.dec.move_ownership', section: 'need', kind: 'need_item', group: 'decisions', groupLabel: 'Decisions', groupWhen: 'Week 1', owner: 'vandana', due: '2026-08-14', label: 'Who owns a move', detail: 'She keeps it and licenses it to you, or it becomes 1MWD content. This one has to be answered before a single upload exists' },
    { key: 'need.dec.price', section: 'need', kind: 'need_item', group: 'decisions', groupLabel: 'Decisions', groupWhen: 'Week 1', owner: 'vandana', due: '2026-08-14', label: 'Membership price', detail: 'The model uses $75/year; confirm or set' },

    // — Access
    { key: 'need.acc.dns', section: 'need', kind: 'need_item', group: 'access', groupLabel: 'Access', groupWhen: 'Weeks 1–2', owner: 'vandana', due: '2026-08-21', label: 'Domain control', detail: 'For all four sites, or DNS delegated to us' },
    { key: 'need.acc.stripe', section: 'need', kind: 'need_item', group: 'access', groupLabel: 'Access', groupWhen: 'Weeks 1–2', owner: 'vandana', due: '2026-08-21', label: 'Stripe account', detail: 'Under House of Tigris Media, or authority to open it' },
    { key: 'need.acc.dev_accounts', section: 'need', kind: 'need_item', group: 'access', groupLabel: 'Access', groupWhen: 'Not needed', owner: 'steph', label: 'Apple and Google developer accounts — handled', detail: 'FlowBond publishes under its own developer accounts, so the slowest external dependency in the project is off your list entirely. Transferring to House of Tigris later is a console operation, not a resubmission' },
    { key: 'need.acc.brand_assets', section: 'need', kind: 'need_item', group: 'access', groupLabel: 'Access', groupWhen: 'Weeks 1–2', owner: 'vandana', due: '2026-08-21', label: 'Brand assets', detail: 'Goddess mark, the heart gradient, the 1B♥ watermark, typefaces and licences' },
    { key: 'need.acc.social', section: 'need', kind: 'need_item', group: 'access', groupLabel: 'Access', groupWhen: 'Weeks 1–2', owner: 'vandana', due: '2026-08-21', label: 'Social accounts', detail: 'For 1MWD, We Speak Dance and 1BH, for scheduling and auto-clip posting' },

    // — Legal
    { key: 'need.leg.entity', section: 'need', kind: 'need_item', group: 'legal', groupLabel: 'Legal', groupWhen: 'Weeks 2–4', owner: 'vandana', due: '2026-08-21', label: 'Contracting entity confirmed', detail: 'House of Tigris Media as the counterparty' },
    { key: 'need.leg.participant_terms', section: 'need', kind: 'need_item', group: 'legal', groupLabel: 'Legal', groupWhen: 'Weeks 2–4', owner: 'shared', due: '2026-09-04', label: 'Participant terms', detail: 'The video licence a woman grants when she uploads. We draft the technical requirements, your counsel writes it' },
    { key: 'need.leg.privacy', section: 'need', kind: 'need_item', group: 'legal', groupLabel: 'Legal', groupWhen: 'Weeks 2–4', owner: 'shared', due: '2026-09-04', label: 'Privacy posture', detail: 'Your first cohort spans Brazil, the EU and MENA, so GDPR and LGPD apply from day one, not later' },
    { key: 'need.leg.age', section: 'need', kind: 'need_item', group: 'legal', groupLabel: 'Legal', groupWhen: 'Weeks 2–4', owner: 'vandana', due: '2026-08-28', label: 'Minimum age policy', detail: 'This determines what we build for sign-up, so it can\'t be decided after launch' },
    { key: 'need.leg.teacher_agreement', section: 'need', kind: 'need_item', group: 'legal', groupLabel: 'Legal', groupWhen: 'Weeks 2–4', owner: 'vandana', due: '2026-09-11', label: 'Guest teacher agreement', detail: 'A one-page template we can reuse every month, with the payout split in it' },

    // — Content & people
    { key: 'need.con.cohort', section: 'need', kind: 'need_item', group: 'content', groupLabel: 'Content & people', groupWhen: 'Weeks 4–8', owner: 'vandana', due: '2026-09-25', label: 'First cohort list', detail: 'The mix of recognised names and grassroots leaders, with contact and consent' },
    { key: 'need.con.her_move', section: 'need', kind: 'need_item', group: 'content', groupLabel: 'Content & people', groupWhen: 'Weeks 4–8', owner: 'vandana', due: '2026-09-18', label: 'Your own move', detail: 'Uploaded first, seeded before anyone else joins' },
    { key: 'need.con.class_calendar', section: 'need', kind: 'need_item', group: 'content', groupLabel: 'Content & people', groupWhen: 'Weeks 4–8', owner: 'vandana', due: '2026-09-25', label: 'Monthly class calendar', detail: 'Teachers and speakers booked at least two months out' },
    { key: 'need.con.moderation_owner', section: 'need', kind: 'need_item', group: 'content', groupLabel: 'Content & people', groupWhen: 'Weeks 4–8', owner: 'vandana', due: '2026-10-02', label: 'Moderation owner', detail: 'One named person on your team who reviews the upload queue daily' },
    { key: 'need.con.s2_date', section: 'need', kind: 'need_item', group: 'content', groupLabel: 'Content & people', groupWhen: 'Weeks 4–8', owner: 'vandana', label: 'S2 end-card date', detail: 'The moment you have it, so launch sequencing locks to it' },

    /* ============================================================ */
    /* 08 — MONEY                                                    */
    /* ============================================================ */
    {
      key: 'money.head',
      section: 'money',
      kind: 'section_head',
      annotatable: false,
      index: '09',
      eyebrow: 'The model',
      title: 'Year 1 has no technology line',
      dek:
        'Your budget allocates $1,021,000 across eight categories. Technology & Platform appears in the P&L at $80,000 — but starting in Year 2. In Year 1 it\'s zero, while the membership, events and brand-partner revenue lines all depend on the platform existing in Year 1. That gap is the reason this conversation is worth having now rather than after the raise closes.',
    },
    {
      key: 'money.stat_zero',
      section: 'money',
      kind: 'stat',
      accent: 'gold',
      figure: '$0',
      label: 'Year 1 technology in the current model',
      body: 'While Year 1 revenue includes $15,000 of membership and $60,000 of events — both of which run through the platform.',
    },
    {
      key: 'money.stat_scratch',
      section: 'money',
      kind: 'stat',
      accent: 'gold',
      figure: '$400K+',
      label: 'Cost to build this from scratch',
      body: 'Identity, payments, ledger, referral graph, media pipeline and two mobile apps, at market rate with a hired team, in roughly nine months.',
    },
    {
      key: 'money.stat_built',
      section: 'money',
      kind: 'stat',
      accent: 'rainbow',
      figure: 'Already built',
      label: 'The five systems underneath',
      body: 'Identity, split payments, referral graph, ledger and infrastructure are running in production today, carrying other products. You\'re paying to connect them, not to invent them.',
    },
    {
      key: 'money.close',
      section: 'money',
      kind: 'prose',
      body: [
        'The Year 1 budget needs a technology line before the SAFE closes. An investor who reads the current model will ask where the app comes from, and the strongest possible answer is that it already exists, it is already being built, and here is exactly what it costs to run.',
      ],
    },

    /* ============================================================ */
    /* 09 — THE DEAL                                                 */
    /* ============================================================ */
    {
      key: 'deal.head',
      section: 'deal',
      kind: 'section_head',
      annotatable: false,
      index: '10',
      eyebrow: 'The structure',
      title: 'The deal is on.',
      dek:
        'This is no longer an ask with three options attached to it. The structure is settled, and it is deliberately simple: ten percent vested to Steph personally, the FlowBond stack supplied at cost to build on, and fees that arrive later — as monetisation switches on and funding lands — rather than up front.',
    },
    {
      key: 'deal.equity',
      section: 'deal',
      kind: 'stat',
      accent: 'rainbow',
      figure: '10%',
      label: 'Vested to Steph Ferrera, personally',
      body:
        'Ten percent of House of Tigris Media, vesting to Steph Ferrera as a person rather than to a vendor — because what you are getting is a founder in the seat, not an agency on a retainer. She builds the platform: identity, the Dance Chain, Hearts, payments, the feed, the class page, the auto-clip renderer and both mobile apps.',
    },
    {
      key: 'deal.lead',
      section: 'deal',
      kind: 'card',
      owner: 'steph',
      title: 'Steph Ferrera takes the technology lead',
      body:
        'Founder and CEO of FlowBond, in the lead role for technology on 1 Million Women Dance. One person accountable for the whole stack — architecture, delivery, security, and the team around it — rather than a vendor you have to manage. The vesting is what makes that real: she is in it on the same terms you are.',
      tech: 'Lead · architecture · delivery · security',
    },
    {
      key: 'deal.expenses',
      section: 'deal',
      kind: 'callout',
      owner: 'shared',
      title: 'The FlowBond stack, supplied at cost',
      body: [
        'A separate, short agreement lets 1 Million Women Dance build on the FlowBond stack — identity, the ledger, split payments, the referral graph, the media pipeline, the live gamified layer — and pay only what it actually costs to run. Hosting and edge delivery, storage and transcode, generation credits, third-party services: billed at consumption, with no margin on top while you are pre-revenue.',
        'That is the whole point of building on something that already exists. You are not funding its invention, and you are not paying platform rent for the privilege of being early.',
      ],
    },
    {
      key: 'deal.contracts',
      section: 'deal',
      kind: 'card',
      owner: 'shared',
      title: 'Fees arrive as the money does',
      body:
        'Platform fees switch on down the road, not now — as monetisation items go live and as funding lands. Membership billing, class ticketing, the perks catalogue, brand-partner activations, campaign work: each one gets its own short paper as it arrives, sized to what it earns. Nothing is owed against revenue that does not exist yet, which keeps the SAFE clean and the runway long.',
      tech: 'On monetisation · on funding · never before',
    },
    {
      key: 'deal.close',
      section: 'deal',
      kind: 'prose',
      body: [
        'Ten percent vested to a founder who is building it herself, a stack supplied at cost, and fees that only begin when there is something to take them from. Three short papers instead of one long negotiation — which is what lets us start on Monday rather than waiting for counsel to finish choosing between hypotheticals.',
        'The rest of it is the part we are actually here for: making the world dance with you.',
      ],
    },

    /* ============================================================ */
    /* 09 — NEXT                                                     */
    /* ============================================================ */
    {
      key: 'next.head',
      section: 'next',
      kind: 'section_head',
      annotatable: false,
      index: '11',
      eyebrow: 'Immediate',
      title: 'Seven days, seven things.',
    },
    { key: 'next.01', section: 'next', kind: 'next_item', owner: 'vandana', due: '2026-08-14', n: '01', title: 'Confirm House of Tigris Media as the contracting entity', detail: 'So paperwork can start in parallel with the build.' },
    { key: 'next.02', section: 'next', kind: 'next_item', owner: 'vandana', due: '2026-08-14', n: '02', title: 'Answer the four Dance Hearts rules', detail: 'Thirty minutes on a call. Everything in weeks 6–7 waits on this.' },
    { key: 'next.03', section: 'next', kind: 'next_item', owner: 'vandana', due: '2026-08-14', n: '03', title: 'Decide who owns a move', detail: 'The single answer that cannot be changed after the first upload.' },
    { key: 'next.04', section: 'next', kind: 'next_item', owner: 'shared', due: '2026-08-14', n: '04', title: 'Look at danz.now and tell us what to keep', detail: 'The gamified layer is live. Fifteen minutes on it tells us which parts belong in 1MWD and which do not.' },
    { key: 'next.05', section: 'next', kind: 'next_item', owner: 'vandana', due: '2026-08-14', n: '05', title: 'Send the brand asset pack', detail: 'Goddess mark, heart gradient, watermark, typefaces and their licences.' },
    { key: 'next.06', section: 'next', kind: 'next_item', owner: 'vandana', due: '2026-08-14', n: '06', title: 'Delegate DNS for the four domains', detail: 'Or add us so the sites can go live in week two.' },
    { key: 'next.07', section: 'next', kind: 'next_item', owner: 'shared', due: '2026-08-14', n: '07', title: 'Pick a commercial structure', detail: 'A, B or C. Then the Year 1 budget gets its technology line and the model is investor-ready.' },
  ],
};

export default room1mwd;
